### ISSUE TITLE
Support for OS X

### ISSUE THREAD

**Issue by AppleTechy** [NovaGL/HarmonyHubControl#1]
I see you added support for OS X but how do I run it  on Mac? Sorry probably a really dumb question but everything file wise is based on windows.

**Comment by AppleTechy** [comment]
@NovaGL Can you walk me through the general steps?

**Comment by NovaGL** [comment]
Open the file in terminal just remove the .exe the commands are the same.

**Comment by AppleTechy** [comment]
@NovaGL You on Slack? Which file should I open in Terminal? cpp? My computer defaults that to Xcode. Also then when trying to implment this into my Homebridge can I still use the homebridge-cmd or is there a homebridge-terminal or homebridge-applescript that I have to use?

**Comment by AppleTechy** [comment]
What file am I suppose to open in terminal? And does it have to be located in the Applications folder on the computer? Do you have the have the official Logitech harmony app running in the background?

**Comment by AppleTechy** [comment]
armonyHubControl-master/HarmonyHubControl.cpp: line 1: /Applications: is a directory
Desktop/HarmonyHubControl-master/HarmonyHubControl.cpp: line 2: Permission: command not found
Desktop/HarmonyHubControl-master/HarmonyHubControl.cpp: line 3: syntax error near unexpected token `('
Desktop/HarmonyHubControl-master/HarmonyHubControl.cpp: line 3: `  of this software and associated documentation files (the "Software"), to deal '
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
This is what I get when I try to run it in terminal. What did I miss up?

**Comment by NovaGL** [comment]
Like I said earlier you have to go to the releases folder.

The app is located here https://github.com/NovaGL/HarmonyHubControl/tree/master/Release/OSX

It is independent of the harmony app

**Comment by AppleTechy** [comment]
@novagl I  literally figured that out like 5 seconds ago. Do I have to move it to the Applications folder for it to run correctly? And When I ran it I got Syntax:
HarmonyHubControl [harmony_ip] [command (optional)]
    where command can be any of the following:
        list_activities
        list_activities_raw
        get_current_activity_id
        get_current_activity_id_raw
        start_activity [ID]
        list_devices
        list_devices_raw
        list_device_commands [deviceId]
        list_device_commands_raw [deviceId]
        issue_device_command [deviceId] [command]
        get_config
        get_config_raw

logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by NovaGL** [comment]
Maybe read what it says before commenting.

Just typing HarmonyHubControl will not do anything, you need to have the Hub IP. 

It's a Do It Yourself program nothing is automated.

Can you please just do some trial and error see if you can figure it out yourself, that way you will be able to learn much faster.

**Comment by AppleTechy** [comment]
Ok. sorry for the dumb question.. I though since you had it bundled that it was automated. If I run it do I only need to have the release in the Application folder, then does it create its own library to save activites.json, etc?

**Comment by NovaGL** [comment]
It creates all the JSON in the same folder, the json isn't needed for the app to run, its just for your reference.

**Comment by AppleTechy** [comment]
Whoops ok. Then I will move it back into its folder.

**Comment by AppleTechy** [comment]
Is there an easy way to find the ip address of your hub without going and digging through your router? Does either the Desktop app or mobile app tell you?

**Comment by NovaGL** [comment]
There are node apps, I don't think my app is for you, its too DIY.

**Comment by AppleTechy** [comment]
No I understand what I am doing now. The setup confused me as the documentation made little sense to me plus, I am tired so I must admit my mind is not firing on all cylinders right now which didn't help :P I also wanted to know if there was an easy way to find the ip as must apps have a hidden feature that allows you to do so and I have like 100 devices on my network so it is a pain to find individual ips. Plus your app is straight forward not complicated at all. Thanks for putting up with my questions so far.

**Comment by NovaGL** [comment]
Glad to hear, would you like to suggest alternative wording?

As I just forked it and made some changes so it's not all my wording. That's why I don't know how to find the IP for you, open the Harmony app on your mobile device and it should say it.

**Comment by AppleTechy** [comment]
I poked around a little bit in the harmony mobile app and I couldn't find a button for advanced info on the hub. Might have just missed it the ip though. Finally got the ip address from the router. Now I have one issue. I thought I could just run in terminal HarmonyHubControl [the ip]. Though when I do that it doesn't recognize HarmonyHubControl as a valid command. But when I try and run the application it just ends due to it not having the IP. I know I am missing something but what is it?

**Comment by AppleTechy** [comment]
/Applications/HarmonyHubControl [the ip address]
HARMONY COMMUNICATION LOGIN    : FAILURE
ERROR : connectToHarmony : Unable to connect to specified IP Address on specified Port
This it saying the IP is incorrect. Do I need to specify a port number or anything or did I just some how not find the actual hub address :/ ?

**Comment by NovaGL** [comment]
You have the wrong IP and if you don't include any commands it won't do anything

In the Harmony app settings > about > versions to get the IP address

**Comment by AppleTechy** [comment]
@novagl I purposefully hadn't included any commands as I wanted to limit
the number of issues I had with it to make it easier to figure out if I
screwed anything up. And I had my Ip address correct but it still gives me the login failure. Is there anything else that could be giving me that error? 
**Thanks for the tid-bit about getting the ip in the harmony app

**Comment by NovaGL** [comment]
It works for me, maybe try on linux or pc.

> /harmonyhub/Harmony 192.168.1.10
> LOGITECH WEB SERVICE LOGIN     : BYPASSED
> HARMONY COMMUNICATION LOGIN    : SUCCESS
> HARMONY COMMAND SUBMISSION     : SUCCESS

**Comment by AppleTechy** [comment]
@novagl as I am new to Raspberrian Linux, actually linux is my last choice for OS. Anyway, how would I got about using you app? What would the commands be? Sorry for being such a Noob but I have very little experience with Linux. Thanks for the help!

**Comment by NovaGL** [comment]
The commands are no different than in linux, I am sorry but I can't walk you through it. If you don't understand what I have already said you need to use another plugin. I can't teach you how to use Linux as well.

**Comment by AppleTechy** [comment]
@novagl Totally understand but when trying to use the same command I used
in Mac that worked now doesn't work  When I tried to adopt it for the
system formats on Linux it refused to execute it as a command. Can you just
tell command to start the program? even an example of the command you use would
do. I just need a basis to start. Any help would be much appreciated!

**Comment by NovaGL** [comment]
The release for Linux needs to use the linux file not the mac file. You have to make sure the file is executable by doing chmod a+x HarmonyHubControl. The linux file is only for Raspberry Pi 2.

**Comment by AppleTechy** [comment]
@novagl it turns out that it wasn't an issue of it being executable as I
verified the properties of the device and it found that it was executable.
The issues was I forgot the ./ in front of HarmonyHubControl when trying to
execute it in Terminal. Though is still have the problem that I did on Mac.
"Harmony Communication  Login   : Failure" I have verified that I have the
right IP address. Could the hub be operating on a different port than what
the application is looking for? Is there any debug log or anything that
would be off use to solving this problem?

**Comment by AppleTechy** [comment]
@novagl What port is your app trying to connect to? Running a quick scan on
my network I discovered my Harmony Hub is listening to ports 5222, 8088,
8222.

**Comment by NovaGL** [comment]
I can assure you its a problem on your end, its not a problem with the ports or the application. I have tested all 3 versions and they all login to my hub, I suggest you look at what you are typing as I believe you are typing it wrong.

**Comment by AppleTechy** [comment]
@novagl Success! The light bulb went off in my head today when I was
thinking now about the plugin. My issue was I was putting my IP address in
brackets instead of just "./HarmonyHubControl ipaddess" My suggestion would
to edit the brackets out of the given instructions as to make it clearer of
the actual command. If you don't want to edit the command out I suggest a
screenshot of the actual command typed into terminal or make a note some
where in the readme of the program. Thank you for putting up with some of
my dumb relative questions. :)

**Comment by NovaGL** [comment]
No, because I wrote above how to do it, not to be rude, but you need to read what I write.

Look above where I wrote "It works for me, maybe try on linux or pc."

**Comment by AppleTechy** [comment]
This is the only message that you have it not in brackets and to be
completely honest that was about 11pm my time so I just missed it. I think
on my end it would have been helpful if I had told you the exact command I
had been using as it would have been caught real fast. Sorry for any
miscommunication on my part.
