### ISSUE TITLE
HARMONY COMMUNICATION LOGIN : FAILURE ERROR : connectToHarmony : Unable to connect to specified IP Address on specified Port

### ISSUE THREAD

**Issue by astanid** [NovaGL/HarmonyHubControl#4]
`HARMONY COMMUNICATION LOGIN : FAILURE ERROR : connectToHarmony : Unable to connect to specified IP Address on specified Port`
Got this message every time i try to connect to hub :(
How can it be solved ?

**Comment by NovaGL** [comment]
Guessing due to the age, you no longer want an answer and have found a better repo.
If you think this is an error reopen this

**Comment by wkearney99** [comment]
Just trying it now and running into the same error.  The hub pings on the IP address.  But apparently the Hubs no longer support local control via 5222.  They use websockets on 8088 now?

**Comment by NovaGL** [comment]
You have to enable xmpp in the harmony app
