### ISSUE TITLE
Logitech web service response does not contain a login authorization token

### ISSUE THREAD

**Issue by clemon79** [NovaGL/HarmonyHubControl#5]
I've been using this on a Raspberry Pi with Home Assistant, and it WAS working fine, but now I get the "Logitech web service response does not contain a login authorization token" error if I run a command line from any directory that does NOT have HarmonyHub.AuthorizationToken in it. If I copy that file into another directory, that directory will then work.

The problem is that my Home Assistant scripts are not working, which execute the exact same command. So I think I need to know what directory to copy HarmonyHub.AuthorizationToken so it will, or how to include the HarmonyHubControl path in a configuration file someplace.

Any ideas?

**Comment by longunmin** [comment]
Was there ever a solution for this, as I just started experiencing the same issue? I have the Token file in the directory, but it still fails?

**Comment by clemon79** [comment]
Honestly I am not totally sure. I've since switched to the baked-into-HASS Harmony support, but I don't remember if I resolved this issue first or if this was the impetus to move over.

**Comment by NovaGL** [comment]
This repo is not maintained anymore.
