### ISSUE TITLE
Is this project still alive or should I fork my own?

### ISSUE THREAD

**Issue by gordonb3** [NovaGL/HarmonyHubControl#7]
Bottom line: the code presented here does not work with my HarmonyHub. The only activity I get is `PowerOff` and I get no devices and commands. Investigating the code I found that it expects the HarmonyHub to return json data in a specific field order that does not match mine.

I've started rewriting the parser functions using jsoncpp (why reinvent the wheel, right?) and am currently able to list activities, devices and commands. It's far from (CPU) optimal yet though. Will you accept Pull Requests?

**Comment by NovaGL** [comment]
Sorry for never replying I didn't get notifications that, I had issues here.

Due to the fact the API has changed I don't think I am going to maintain it, but if you want to do a PR feel free.

I only created this repo as a clone for the sourceforge one.

**Comment by gordonb3** [comment]
No worries. I just noticed there had not been any activity to this project for quite some time. I did some work on it to make it run with my Hub, but never transferred it to a new project. As you say the API is now broken by Logitech, so it's back to the drawing board.

**Comment by yajrendrag** [comment]
see here - https://community.logitech.com/s/question/0D55A00008D4bZ4SAJ/harmony-hub-firmware-update-fixes-vulnerabilities

Logitech seems to be listening to the feedback and has restored XMPP functionality via a beta and seems to be on a path to make that a regular feature soon

**Comment by NovaGL** [comment]
Thanks. I'm not maintaining this anymore I moved to websocket and node-red happy to share if you want I made another repo for diy stuff.

**Comment by yajrendrag** [comment]
gotcha, thanks.  i haven't had any issues with it, but all i do are a few button presses.  looks like i can follow the diy-harmonyhub instructions and do similar over http & websockets.. will try and post questions, if any, on the other repo
