### ISSUE TITLE
Cannot list devices or activities

### ISSUE THREAD

**Issue by TellTheStar** [NovaGL/HarmonyHubControl#9]
I can't use the list_activities or list_devices. I get nothing returned (no devices listed, and only the -1 activity listed). If I try to start the -1 activity it does work though. Also if I retrive the ID from "get_current_activity_id" I can start/stop that activity. What can be the issue?

Image shows "list_devices".
![image](https://user-images.githubusercontent.com/5111849/61329079-c0e08100-a81c-11e9-8d34-8dd95309ff94.png)

**Comment by NovaGL** [comment]
Sorry for the delay, I don't have notifications on for this repo.

Did you manage to solve your problem? Make sure you have XMPP support enabled in the developer options for this app to work.

**Comment by SXXXR** [comment]
I have the same issue. Does annoy know a fix for this?

**Comment by rEd2k** [comment]
Same issue here, I get no output for devices and activities, I think the only way to get the ID's is to use the "get_config" command and then manually look through all ID's and then send the device command that way... Not sure. Please help! This is the only command line harmony hub program I can even get to work and I tried ALL of the rest and it seems and they all require some kind of dependency that never seems to work! Thank you ;)

**Comment by tribefan41** [comment]
I am having the exact same problem. I able to communicate with the hub and pull the config file, but I can't pull an accurate list of devices or send commands successfully. Even though the Harmony line was discontinued, this app has so much potential for us HTPC enthusiasts. I really hope there's a solution out there.

EDIT: I've figured out how to control devices, but I'm not able to start or stop activities. Do I use the activity label to start an activity?

e.g., HarmonyHubControl.exe 192.168.0.55 start_activity Roku

Also, what are the risks inherent in enabling XMPP?

EDIT 2: Feel so close!! If I could just figure out how to properly disclose activities in the CLI I'd be in business. Using the activity's label as it appears in the config is not working (e.g., Roku in my example above).

**Comment by bmalrat** [comment]
I pushed a MR to fix the json parser to restore the feature #11

**Comment by NovaGL** [comment]
@bmalrat would you like me to make you a contributor so you can approve the PRs?

**Comment by bmalrat** [comment]
Hello @NovaGL, you could add me if you want but on that case it will be a self approve.  
Since the project is not a big one and not very active it's not a big problem
